# Data Retrieval

In [3]:
import requests
from bs4 import BeautifulSoup
from chembl_webresource_client.new_client import new_client
import pandas as pd
import json

/Users/vlad/Documents/University/Master-MIND/DALAS-Project/.venv/lib/python3.11/site-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## ChEMBL

Python API client tutorial:
https://hub.2i2c.mybinder.org/user/chembl-chembl_webresource_client-7wkmmjs9/notebooks/demo_wrc.ipynb

In [4]:
molecule = new_client.molecule
drug_indication = new_client.drug_indication
target = new_client.target
activity = new_client.activity

### Get MeSH IDs of Autoimmune diseases

In [5]:
# Exctract all MeSH terms of autoimmune diseases
# Site with MeSH terms with autoimmune diseases
url = "https://www.ncbi.nlm.nih.gov/mesh?Db=mesh&Cmd=DetailsSearch&Term=%22Autoimmune+Diseases%22%5BMeSH+Terms%5D"
response = requests.get(url)
if response.status_code == 200:
    html_content = response.text
    soup = BeautifulSoup(html_content, "html.parser")

soup.find_all("span", string="Autoimmune Diseases")
autoimm_ul = soup.find("span", string="Autoimmune Diseases").find_all_next("ul")
autoimm_ul[8].find_all("a")[0].get("href")

mesh_ids = []

for disease_a in autoimm_ul[8].find_all("a"):
    disease_url = disease_a.get('href')
    response = requests.get(f'https://www.ncbi.nlm.nih.gov{disease_url}')
    if response.status_code == 200:
        html_content = response.text
        disease_soup = BeautifulSoup(html_content, "html.parser")
        mesh_ids.append(disease_soup.find("p", string=lambda text: text and text.startswith("MeSH Unique ID:")).text.split()[-1])

In [6]:
print(f'Autoimmune diseases: {len(mesh_ids)}')

Autoimmune diseases: 50

In [7]:
autoimmune_ind = drug_indication.filter(mesh_id__in=mesh_ids)
indications_df = pd.DataFrame(autoimmune_ind)
chembl_ids = pd.unique(indications_df["molecule_chembl_id"]).tolist()
autoimmune_drugs = molecule.filter(molecule_chembl_id__in = chembl_ids, max_phase__gte = 3)
drugs_df = pd.DataFrame(autoimmune_drugs)

In [8]:
print(f'Drug-disease indications: {len(indications_df)}')
print(f'Drugs used for autoimmune diseses: {len(drugs_df)}')
print(f'Biologics: {drugs_df["biotherapeutic"].notnull().sum()}')
print(f'Small molecules: {drugs_df["biotherapeutic"].isnull().sum()}')

Drug-disease indications: 1256
Drugs used for autoimmune diseses: 515
Biologics: 125
Small molecules: 390

In [9]:
matches_df = pd.merge(indications_df, drugs_df, on="molecule_chembl_id")

In [10]:
drugs_df

,atc_classifications,availability_type,biotherapeutic,black_box_warning,chemical_probe,chirality,cross_references,dosed_ingredient,first_approval,first_in_class,...,prodrug,structure_type,therapeutic_flag,topical,usan_stem,usan_stem_definition,usan_substem,usan_year,veterinary,withdrawn_flag
0,"[C01EB03, M01AB01, M01AB51, M02AA23, S01BC01]",1.0,None,1,0,2,"[{'xref_id': 'indomethacin', 'xref_name': 'ind...",True,1965.0,0,...,0,MOL,True,True,None,None,None,1963.0,0,False
1,"[J01MA02, S01AE03, S02AA15, S03AA07]",1.0,None,1,0,2,"[{'xref_id': 'ciprofloxacin', 'xref_name': 'ci...",True,1987.0,0,...,0,MOL,True,True,-oxacin,antibacterials (quinolone derivatives),-oxacin,1987.0,0,False
2,[N05BA01],1.0,None,1,0,2,"[{'xref_id': 'diazepam', 'xref_name': 'diazepa...",True,1963.0,0,...,0,MOL,True,True,-azepam,antianxiety agents (diazepam type),-azepam,1963.0,0,False
3,"[L01EG04, L04AH01, S01XA23]",1.0,None,1,1,1,"[{'xref_id': 'sirolimus', 'xref_name': 'siroli...",True,1999.0,0,...,0,MOL,True,True,-imus,immunosuppressives,-imus,1993.0,0,False
4,[],1.0,None,1,1,1,[],False,1994.0,0,...,0,MOL,True,True,-imus,immunosuppressives,-imus,1992.0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,[],1.0,None,1,0,1,"[{'xref_id': 'human/EPAR/zilbrysq', 'xref_name...",True,2023.0,0,...,0,NONE,True,False,-coplan,complement ligand inhibitors,-coplan,NaN,0,False
511,[],1.0,None,1,0,1,"[{'xref_id': 'upadacitinib%20hemihydrate', 'xr...",True,2019.0,0,...,0,MOL,True,False,-tinib,tyrosine kinase inhibitors: tyrosine kinase in...,-tinib (-citinib),NaN,0,False
512,[L01XX27],1.0,None,1,0,2,"[{'xref_id': 'arsenic%20trioxide', 'xref_name'...",True,2000.0,0,...,0,MOL,True,False,None,None,None,2001.0,0,False
513,[],1.0,None,1,0,2,[],True,2023.0,0,...,0,MOL,True,False,-trombopag,thrombopoetin agonists,-trombopag,NaN,0,False
514,[],NaN,None,0,0,2,[],False,NaN,0,...,0,MOL,False,False,-ium,quaternary ammonium derivatives,-ium,NaN,0,False

In [11]:
indications_df

,drugind_id,efo_id,efo_term,indication_refs,max_phase_for_ind,mesh_heading,mesh_id,molecule_chembl_id,parent_molecule_chembl_id
0,22607,EFO:0000685,rheumatoid arthritis,"[{'ref_id': 'NCT00048568,NCT00048581,NCT000489...",4.0,"Arthritis, Rheumatoid",D001172,CHEMBL1201823,CHEMBL1201823
1,22633,EFO:0000685,rheumatoid arthritis,"[{'ref_id': 'NCT00049751,NCT00195650,NCT001956...",4.0,"Arthritis, Rheumatoid",D001172,CHEMBL1201580,CHEMBL1201580
2,22744,EFO:0004991,Myasthenia gravis,"[{'ref_id': 'NCT01727193', 'ref_type': 'Clinic...",3.0,Myasthenia Gravis,D009157,CHEMBL1542,CHEMBL1542
3,22837,EFO:0002609,juvenile idiopathic arthritis,"[{'ref_id': 'NCT00426218', 'ref_type': 'Clinic...",4.0,"Arthritis, Juvenile",D001171,CHEMBL1201834,CHEMBL1201834
4,22868,EFO:0002609,juvenile idiopathic arthritis,"[{'ref_id': 'NCT00652925,NCT00807846', 'ref_ty...",4.0,"Arthritis, Juvenile",D001171,CHEMBL118,CHEMBL118
...,...,...,...,...,...,...,...,...,...
1251,156753,MONDO:0007915,systemic lupus erythematosus,"[{'ref_id': 'ZOLACABTAGENE AUTOLEUCEL', 'ref_t...",1.0,"Lupus Erythematosus, Systemic",D008180,CHEMBL6068475,CHEMBL6068475
1252,156910,MONDO:0007915,systemic lupus erythematosus,"[{'ref_id': 'NCT01405196', 'ref_type': 'Clinic...",2.0,"Lupus Erythematosus, Systemic",D008180,CHEMBL6068160,CHEMBL6068160
1253,157057,EFO:1001466,Graves ophthalmopathy,"[{'ref_id': 'NCT02393183', 'ref_type': 'Clinic...",2.0,Graves Ophthalmopathy,D049970,CHEMBL6068503,CHEMBL6068503
1254,157176,MONDO:0005147,type 1 diabetes mellitus,"[{'ref_id': 'NCT03272269', 'ref_type': 'Clinic...",1.0,"Diabetes Mellitus, Type 1",D003922,CHEMBL6068583,CHEMBL6068583
1255,157245,EFO:0007160,autoimmune thrombocytopenic purpura,"[{'ref_id': 'label/2023/216774s000lbl.pdf', 'r...",4.0,"Purpura, Thrombocytopenic, Idiopathic",D016553,CHEMBL6068328,CHEMBL461101

### Targets and Mechanisms

TODO: get lists of molecular targets / mechanisms for each drugs

It will be useful for graph models

In [12]:
target = new_client.target
mechanism = new_client.mechanism

In [13]:
drug_mech = mechanism.filter(molecule_chembl_id__in = chembl_ids[2])
print(f'{len(drug_mech)=}')
print(drug_mech[0])
print(drug_mech[1])

len(drug_mech)=2
{'action_type': 'INHIBITOR', 'binding_site_comment': None, 'direct_interaction': 1, 'disease_efficacy': 1, 'max_phase': 4, 'mec_id': 1744, 'mechanism_comment': 'Prodrug enzyme: hypoxanthine-guanine phosphoribosyl transferase (HGPRT; EC 2.4.2.8)', 'mechanism_of_action': 'Amidophosphoribosyltransferase inhibitor', 'mechanism_refs': [{'ref_id': '18506437', 'ref_type': 'PubMed', 'ref_url': 'http://europepmc.org/abstract/MED/18506437'}], 'molecular_mechanism': 1, 'molecule_chembl_id': 'CHEMBL1542', 'parent_molecule_chembl_id': 'CHEMBL1542', 'record_id': 1343926, 'selectivity_comment': None, 'site_id': None, 'target_chembl_id': 'CHEMBL2362992', 'variant_sequence': None}
{'action_type': 'INHIBITOR', 'binding_site_comment': None, 'direct_interaction': 1, 'disease_efficacy': 1, 'max_phase': 4, 'mec_id': 1874, 'mechanism_comment': 'Prodrug enzyme: hypoxanthine-guanine phosphoribosyl transferase (HGPRT; EC 2.4.2.8)', 'mechanism_of_action': 'DNA inhibitor', 'mechanism_refs': [{'ref_id': '18506437', 'ref_type': 'PubMed', 'ref_url': 'http://europepmc.org/abstract/MED/18506437'}], 'molecular_mechanism': 1, 'molecule_chembl_id': 'CHEMBL1542', 'parent_molecule_chembl_id': 'CHEMBL1542', 'record_id': 1343926, 'selectivity_comment': None, 'site_id': None, 'target_chembl_id': 'CHEMBL2311221', 'variant_sequence': None}

In [14]:
drug_targets = target.filter(molecule_chembl_id__in = chembl_ids[0])
print(f'{len(drug_targets)=}')
drug_targets[0]

len(drug_targets)=17803

{'cross_references': [],
 'organism': 'Homo sapiens',
 'pref_name': 'Maltase-glucoamylase',
 'species_group_flag': False,
 'target_chembl_id': 'CHEMBL2074',
 'target_components': [{'accession': 'O43451',
   'component_description': 'Maltase-glucoamylase',
   'component_id': 434,
   'component_type': 'PROTEIN',
   'relationship': 'SINGLE PROTEIN',
   'target_component_synonyms': [{'component_synonym': '3.2.1.20',
     'syn_type': 'EC_NUMBER'},
    {'component_synonym': 'Alpha-1,4-glucosidase', 'syn_type': 'UNIPROT'},
    {'component_synonym': 'Maltase-glucoamylase', 'syn_type': 'UNIPROT'},
    {'component_synonym': 'MGA', 'syn_type': 'GENE_SYMBOL_OTHER'},
    {'component_synonym': 'MGAM', 'syn_type': 'GENE_SYMBOL'},
    {'component_synonym': 'MGAML', 'syn_type': 'GENE_SYMBOL_OTHER'},
    {'component_synonym': 'Synonyms=MGA', 'syn_type': 'GENE_SYMBOL_OTHER'}],
   'target_component_xrefs': [{'xref_id': 'O43451',
     'xref_name': None,
     'xref_src_db': 'AlphaFoldDB'},
    {'xref_id': 'O43451', 'xref_name': None, 'xref_src_db': 'ExpressionAtlas'},
    {'xref_id': 'GO:0005886',
     'xref_name': 'plasma membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0016324',
     'xref_name': 'apical plasma membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0070062',
     'xref_name': 'extracellular exosome',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0070821',
     'xref_name': 'tertiary granule membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0101003',
     'xref_name': 'ficolin-1-rich granule membrane',
     'xref_src_db': 'GoComponent'},
    {'xref_id': 'GO:0003824',
     'xref_name': 'catalytic activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0004339',
     'xref_name': 'glucan 1,4-alpha-glucosidase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0004553',
     'xref_name': 'hydrolase activity, hydrolyzing O-glycosyl compounds',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0004558',
     'xref_name': 'alpha-1,4-glucosidase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0004574',
     'xref_name': 'oligo-1,6-glucosidase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0005515',
     'xref_name': 'protein binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0016160',
     'xref_name': 'amylase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0016798',
     'xref_name': 'hydrolase activity, acting on glycosyl bonds',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0030246',
     'xref_name': 'carbohydrate binding',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0090599',
     'xref_name': 'alpha-glucosidase activity',
     'xref_src_db': 'GoFunction'},
    {'xref_id': 'GO:0000025',
     'xref_name': 'maltose catabolic process',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0005975',
     'xref_name': 'carbohydrate metabolic process',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:0005983',
     'xref_name': 'starch catabolic process',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'GO:1901027',
     'xref_name': 'dextrin catabolic process',
     'xref_src_db': 'GoProcess'},
    {'xref_id': 'HGNC:7043', 'xref_name': 'MGAM', 'xref_src_db': 'HGNC'},
    {'xref_id': 'O43451', 'xref_name': None, 'xref_src_db': 'IntAct'},
    {'xref_id': 'IPR000322',
     'xref_name': 'Glyco_hydro_31_TIM',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR000519',
     'xref_name': 'P_trefoil_dom',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR011013',
     'xref_name': 'Gal_mutarotase_sf_dom',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR013780',
     'xref_name': 'Glyco_hydro_b',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR017853',
     'xref_name': 'Glycoside_hydrolase_SF',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR017957',
     'xref_name': 'P_trefoil_CS',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR025887',
     'xref_name': 'Glyco_hydro_31_N_dom',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR030458',
     'xref_name': 'Glyco_hydro_31_AS',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR030459',
     'xref_name': 'Glyco_hydro_31_CS',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR044913',
     'xref_name': 'P_trefoil_dom_sf',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'IPR048395',
     'xref_name': 'Glyco_hydro_31_C',
     'xref_src_db': 'InterPro'},
    {'xref_id': 'PTHR22762',
     'xref_name': 'ALPHA-GLUCOSIDASE',
     'xref_src_db': 'PANTHER'},
    {'xref_id': 'PTHR22762:SF133',
     'xref_name': 'P-TYPE DOMAIN-CONTAINING PROTEIN',
     'xref_src_db': 'PANTHER'},
    {'xref_id': '2QLY', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '2QMJ', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3CTT', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4T', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4U', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4V', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4W', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4X', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4Y', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3L4Z', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3TON', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '3TOP', 'xref_name': None, 'xref_src_db': 'PDB'},
    {'xref_id': '2QLY', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '2QMJ', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3CTT', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4T', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4U', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4V', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4W', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4X', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4Y', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3L4Z', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3TON', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': '3TOP', 'xref_name': 'A', 'xref_src_db': 'PDBe'},
    {'xref_id': 'PF00088', 'xref_name': 'Trefoil', 'xref_src_db': 'Pfam'},
    {'xref_id': 'PF01055',
     'xref_name': 'Glyco_hydro_31_2nd',
     'xref_src_db': 'Pfam'},
    {'xref_id': 'PF13802',
     'xref_name': 'Gal_mutarotas_2',
     'xref_src_db': 'Pfam'},
    {'xref_id': 'PF21365',
     'xref_name': 'Glyco_hydro_31_3rd',
     'xref_src_db': 'Pfam'},
    {'xref_id': 'PA30778',
     'xref_name': 'maltase-glucoamylase',
     'xref_src_db': 'PharmGKB'},
    {'xref_id': 'O43451', 'xref_name': None, 'xref_src_db': 'Pharos'},
    {'xref_id': 'R-HSA-189085',
     'xref_name': 'Digestion of dietary carbohydrate',
     'xref_src_db': 'Reactome'},
    {'xref_id': 'R-HSA-6798695',
     'xref_name': 'Neutrophil degranulation',
     'xref_src_db': 'Reactome'},
    {'xref_id': 'E7ER45',
     'xref_name': 'Maltase-glucoamylase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'O43451',
     'xref_name': 'Maltase-glucoamylase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q0VAX6',
     'xref_name': 'Maltase-glucoamylase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q75ME7',
     'xref_name': 'Maltase-glucoamylase',
     'xref_src_db': 'UniProt'},
    {'xref_id': 'Q86UM5',
     'xref_name': 'Maltase-glucoamylase',
     'xref_src_db': 'UniProt'}]}],
 'target_type': 'SINGLE PROTEIN',
 'tax_id': 9606}

## Disease Involved Molecules and Mechanisms

TODO: find a nice database and match target / mechnisms IDs with drugs

## Clinical Trials Metadata

TODO: explore further the variables proposed 

Documentation: https://clinicaltrials.gov/data-api/api

API Server: https://clinicaltrials.gov/api/v2

In [ ]:
# TODO: get NCT IDs for all indications and get their timestamps, 
# for indictions from ChEMBL, I guess that we need only timestamps 
# and maybe some other metadata, but we consider them sucessfull by default 
# (otherwise they will not appear in indications)

# TODO: so we need to do the same thing but for all pairs drug - disease 
# using queries and filters of ClinicalTrials API and access the global outcome
# - success, failure, unknown

test_row = 0
ind_refs = indications_df["indication_refs"][test_row]
for ref in ind_refs:
    if ref["ref_type"] == "ClinicalTrials":
        ref_ids = ref["ref_id"].split(",")
ref_ids[:5]

['NCT00048568', 'NCT00048581', 'NCT00048932', 'NCT00095147', 'NCT00122382']

In [ ]:
test_ref_id = ref_ids[0]
# TODO: maybe get all trials at ones with a single query 
# searching in list of all ids with `query.id` but will need to handle pagination

# TODO: request only needed fields
# e.g. https://clinicaltrials.gov/api/v2/studies?query=trastuzumab&fields=protocol_section.status_module.overall_status,results_section.outcome_measure_list.outcome_measure.analysis_list.analysis.p_value

nct_url = f"https://clinicaltrials.gov/api/v2/studies/{test_ref_id}?format=json"
nct_response = requests.get(nct_url)
nct_info = nct_response.json()
print(json.dumps(nct_info, indent=2))

{
  "protocolSection": {
    "identificationModule": {
      "nctId": "NCT00048568",
      "orgStudyIdInfo": {
        "id": "IM101-102"
      },
      "organization": {
        "fullName": "Bristol-Myers Squibb",
        "class": "INDUSTRY"
      },
      "briefTitle": "A Phase III Study of Abatacept (BMS-188667) in Patients With Active Rheumatoid Arthritis and Inadequate Response to Methotrexate",
      "officialTitle": "A Phase 3, Multi-Center, Randomized, Double-Blind, Placebo-Controlled Study and Open-Label Study to Evaluate the Efficacy and Safety of Abatacept in Combination Therapy With Methotrexate Versus Methotrexate Alone in Subjects With Active Rheumatoid Arthritis and Inadequate Response to Methotrexate"
    },
    "statusModule": {
      "statusVerifiedDate": "2011-10",
      "overallStatus": "COMPLETED",
      "expandedAccessInfo": {
        "hasExpandedAccess": false
      },
      "startDateStruct": {
        "date": "2002-12"
      },
      "primaryCompletionDateStruct": {
        "date": "2009-10",
        "type": "ACTUAL"
      },
      "completionDateStruct": {
        "date": "2009-10",
        "type": "ACTUAL"
      },
      "studyFirstSubmitDate": "2002-11-02",
      "studyFirstSubmitQcDate": "2002-11-12",
      "studyFirstPostDateStruct": {
        "date": "2002-11-13",
        "type": "ESTIMATED"
      },
      "resultsFirstSubmitDate": "2011-03-28",
      "resultsFirstSubmitQcDate": "2011-10-26",
      "resultsFirstPostDateStruct": {
        "date": "2011-12-05",
        "type": "ESTIMATED"
      },
      "lastUpdateSubmitDate": "2011-10-26",
      "lastUpdatePostDateStruct": {
        "date": "2011-12-05",
        "type": "ESTIMATED"
      }
    },
    "sponsorCollaboratorsModule": {
      "responsibleParty": {
        "type": "SPONSOR"
      },
      "leadSponsor": {
        "name": "Bristol-Myers Squibb",
        "class": "INDUSTRY"
      }
    },
    "descriptionModule": {
      "briefSummary": "Short Term: The purpose of this clinical research study is to learn if abatacept (BMS-188667) in combination with methotrexate is better than methotrexate alone in participants that have active rheumatoid arthritis and are not responding to methotrexate. The safety of this treatment will also be studied.\n\nLong Term Extension: The purpose of this amendment is to provide participants who have completed the initial 12-month double-blind treatment period the opportunity to receive open label treatment with active drug treatment until abatacept is approved in the local country or until clinical development has been discontinued."
    },
    "conditionsModule": {
      "conditions": [
        "Rheumatoid Arthritis"
      ]
    },
    "designModule": {
      "studyType": "INTERVENTIONAL",
      "phases": [
        "PHASE3"
      ],
      "designInfo": {
        "allocation": "RANDOMIZED",
        "interventionModel": "PARALLEL",
        "primaryPurpose": "TREATMENT",
        "maskingInfo": {
          "masking": "DOUBLE",
          "whoMasked": [
            "PARTICIPANT",
            "INVESTIGATOR"
          ]
        }
      },
      "enrollmentInfo": {
        "count": 1250,
        "type": "ACTUAL"
      }
    },
    "armsInterventionsModule": {
      "armGroups": [
        {
          "label": "Abatacept + Methotrexate",
          "type": "EXPERIMENTAL",
          "description": "Short Term: Abatacept was dosed by weight with participants weighing \\< 60 kg received abatacept 500 mg; participants \u2265 60 kg and \u2264 100 kg received abatacept 750 mg; and participants \\> 100 kg received abatacept 1 g. Participants continued treatment with methotrexate (MTX) either orally or parenterally at a minimum dose of 15 mg.",
          "interventionNames": [
            "Drug: Abatacept",
            "Drug: Methotrexate"
          ]
        },
        {
          "label": "Placebo + Methotrexate",
          "type": "ACTIVE_COMPARATOR",
          "description": "Short Term: Participants received a placebo solution intravenously and methotrexate at the dose employed prior to study enrollment and a minimum of 15 mg.",
          "interventionNames": [
            "Drug: Methotrexate",
            "Drug: Placebo"
          ]
        },
        {
          "label": "Abatacept + Methotrexate Open Label",
          "type": "EXPERIMENTAL",
          "description": "Open Label: Abatacept was dosed intravenously by weight at 10 mg/kg in the OL period under tiered dosing such that participants weighing \\< 60 kg received abatacept 500 mg; participants \u2265 60 kg and \u2264 100 kg received abatacept 750 mg; and participants \\> 100 kg received abatacept 1 g. MTX was continued at the dose used in the DB period.",
          "interventionNames": [
            "Drug: Abatacept",
            "Drug: Methotrexate"
          ]
        }
      ],
      "interventions": [
        {
          "type": "DRUG",
          "name": "Abatacept",
          "description": "Intravenous (IV) Solution, - Weight Titered (500 mg \\< 60 kg); (750 mg 60-100 kg), )1 gram \\> 100 kg), Day 1, Day 15, Day 29; every 28 days thereafter, 1 year",
          "armGroupLabels": [
            "Abatacept + Methotrexate",
            "Abatacept + Methotrexate Open Label"
          ],
          "otherNames": [
            "BMS-188667"
          ]
        },
        {
          "type": "DRUG",
          "name": "Methotrexate",
          "description": "Tablets, Oral, \\>= 15 mg, weekly, 1 year",
          "armGroupLabels": [
            "Abatacept + Methotrexate",
            "Abatacept + Methotrexate Open Label",
            "Placebo + Methotrexate"
          ],
          "otherNames": [
            "MTX"
          ]
        },
        {
          "type": "DRUG",
          "name": "Placebo",
          "description": "IV solution, Intravenous, D5W, Day 1, Day 15, Day 29; every 28 days thereafter, 1 year",
          "armGroupLabels": [
            "Placebo + Methotrexate"
          ]
        }
      ]
    },
    "outcomesModule": {
      "primaryOutcomes": [
        {
          "measure": "Number of American College of Rheumatology 20 (ACR 20) Responders at Day 169",
          "description": "ACR 20 response requires a patient to have a 20% reduction in the number of swollen and tender joints, and a reduction of 20% in three of the following five parameters: physician global assessment of disease, patient global assessment of disease, patient assessment of pain, C-reactive protein or erythrocyte sedimentation rate, and degree of disability in Health Assessment Questionnaire (HAQ) score. A participant achieved a sustained ACR 20 response if the participant had ACR 20 observed for at least 2 consecutive study visits.",
          "timeFrame": "Day 169"
        },
        {
          "measure": "Number of Participants Achieving Clinically Meaningful Improvement in Health Assessment Questionnaire (HAQ) at Day 365",
          "description": "The HAQ-DI includes 20 questions to assess physical function in 8 domains: dressing, arising, eating, walking, hygiene, reach, grip, and common activities. The domain questions are evaluated on a 4-point scale: 0=without any difficulty, 1=with some difficulty, 2=with much difficulty, 3=unable to do. HAQ-DI=sum of worst scores in each domain dividied by the number of domains answered. HAQ-DI ranges from 0 to a maximum overall score of 3.0. Clinically meaningful HAQ response was defined as an improvement of at least 0.3 units from baseline in HAQ DI.",
          "timeFrame": "Day 365"
        },
        {
          "measure": "Baseline and Mean Change From Baseline (BL) in Radiographic Erosion Score Results at Day 365",
          "description": "To assess joint damage progression, the Genant-modified Sharp scoring method was used to evaluate radiographs of hands/wrists and feet for erosions. The erosion score range is 0 (no radiographic damage) to 145 (worst possible radiographic damage). Change from baseline = Post-baseline - Baseline value",
          "timeFrame": "BL (Day 0), Day 365"
        },
        {
          "measure": "Participants With Deaths, Adverse Events (AEs) and SAEs in the Open-Label (OL) Period",
          "description": "AE was defined as any new untoward medical occurrence or worsening of a pre-existing medical condition which does not necessarily have a causal relationship with this treatment. SAE was defined as any untoward medical occurrence that at any dose: results in death, is life-threatening, requires inpatient hospitalization or causes prolongation of existing hospitalization, results in persistent or significant disability/incapacity, is a congenital anomaly/birth defect, results in development of drug dependency or drug abuse, is an important medical event.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Participants With Hematology Values Meeting the Marked Abnormality Criteria in the OL Period",
          "description": "Marked abnormality criteria are: Hemoglobin (HGB): \\>3 g/dL decrease from BL; Hematocrit: \\<0.75 \\* BL; Erythrocytes: \\<0.75 \\* BL; Platelets (PLT): \\<0.67 \\* LLN/\\>1.5 \\* ULN, or if BL \\< LLN then use \\<0.5 \\* BL and \\<100,000 mm\\^3; Leukocytes: \\<0.75 \\* LLN/ \\>1.25 \\* ULN, or if BL\\<LLN then use \\<0.8 \\* BL or \\>ULN, or if BL\\>ULN then use \\>1.2 \\* BL or \\<LLN; neutrophils+bands: \\<1.0 \\* 10\\^3 c/uL; eosinophils: \\>0.750 \\* 10\\^3 c/uL; basophils: \\> 400 mm\\^3; monocytes: \\>2000 mm\\^3; lymphocytes: \\<0.750 \\* 10\\^3 c/uL/ \\>7.50 \\* 10\\^3 c/uL.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Participants With Liver and Kidney Function Values Meeting the Marked Abnormality Criteria in the OL Period",
          "description": "Marked abnormality criteria are: Hemoglobin (HGB): \\>3 g/dL decrease from BL; Hematocrit: \\<0.75 \\* BL; Erythrocytes: \\<0.75 \\* BL; Platelets (PLT): \\<0.67 \\* LLN/\\>1.5 \\* ULN, or if BL \\< LLN then use \\<0.5 \\* BL and \\<100,000 mm\\^3; Leukocytes: \\<0.75 \\* LLN/ \\>1.25 \\* ULN, or if BL\\<LLN then use \\<0.8 \\* BL or \\>ULN, or if BL\\>ULN then use \\>1.2 \\* BL or \\<LLN; neutrophils+bands: \\<1.0 \\* 10\\^3 c/uL; eosinophils: \\>0.750 \\* 10\\^3 c/uL; basophils: \\> 400 mm\\^3; monocytes: \\>2000 mm\\^3; lymphocytes: \\<0.750 \\* 10\\^3 c/uL/ \\>7.50 \\* 10\\^3 c/uL.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Participants With Electrolyte Values Meeting the Marked Abnormality Criteria in the OL Period",
          "description": "Sodium \\< 0.9 \\* LLN or \\> 1.05 \\* ULN or if BL \\< LLN then use \\< 0.95 \\* BL or \\> ULN or if BL \\> ULN then use \\>1.05 \\*BL or \\< LLN; Potassium: \\< 0.9 \\* LLN or \\> 1.1 \\* ULN or if BL \\< LLN then use \\< 0.9 \\* BL or \\> ULN or if BL \\> ULN then use 1.1 \\* BL or \\< LLN; Chloride: \\< 0.9 \\* LLN or \\> 1.1 \\* ULN or if BL \\< LLN then use \\<0.9 \\* BL or \\>ULN or if BL \\> ULN then use \\> 1.1 \\* BL or \\< LLN; Calcium \\<0.8 \\* LLN or \\> 1.2 \\* ULN or if BL \\< LLN then use \\<0.67 \\* BL or \\> ULN or if BL \\> ULN then use \\> 1.3 \\* BL or \\< LLN.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Participants With Glucose, Protein, Metabolites, and Urinalysis Values Meeting the Marked Abnormality Criteria in the OL Period",
          "description": "Glucose: \\< 65 mg/dL or \\> 220 mg/dL; Fasting Glucose: \\<0.8 \\* LLN or \\> 1.5 \\* ULN or if BL \\< LLN then use \\< 0.8 \\* BL or \\> ULN or if BL \\> ULN then use 1.1 \\* BL or \\< LLN; Total protein: \\< 0.9 \\* LLN or 1.1 \\* ULN or if BL \\< LLN then use 0.9 \\* BL or \\> ULN or if BL \\> ULN then use 1.1 \\* BL or \\< LLN; Albumin: \\< 0.9 \\* LLN or if BL \\< LLN then use 0.75 \\* BL; Uric acid: \\> 1.5 \\* ULN or if BL \\> ULN then use \\> 2.0 \\* BL. All urinalysis abnormalities were defined as: if missing BL then use \\>= 2 or if value \\>=4, or if BL = 0 or 0.5 then use \\>= 2, or if BL = 1.0 then use \\>= 3, or if BL = 2.0 then use \\>=4.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Mean BL Immunoglobulins Over Time in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365, Day 729, and Day 1,093.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093"
        },
        {
          "measure": "Mean Change From BL in Immunoglobulins in the OL Period",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093"
        },
        {
          "measure": "Participants With Immunogenicity to Abatacept in the Cumulative DB + OL Period",
          "description": "Participants with titers to abatacept in the DB and OL periods. Serum samples from abatacept-treated adult participants with active Rheumatoid Arthritis (RA) were screened for the presence of drug-specific antibodies using two validated direct-format enzyme-linked immunosorbent assays (ELISAs) to determine the presence of antibodies to abatacept and or CTLA4-T.",
          "timeFrame": "Day 1 to Day 1,821"
        },
        {
          "measure": "Number of Participants Experiencing Clinically Significant Changes in Vital Signs in the OL Period",
          "description": "Vital signs included body temperature, heart rate, and seated blood pressure. Clinically significant changes were defined as those that were not within the normal range for the participant.",
          "timeFrame": "Day 365 to Day 1,821. All changes in participant vital signs were monitored on each day of study drug administration prior to dosing and 60 minutes after dosing."
        },
        {
          "measure": "Number of Participants Experiencing AEs of Special Interest in the OL Period",
          "description": "AEs were defined as any new untoward medical occurrence or worsening of a pre- existing medical condition which does not necessarily have a causal relationship with this treatment. AEs of special interest have been identified to be those which may be associated with the use of immunomodulatory agents or infusion of therapeutic proteins. Acute infusional AEs were defined as those that occurred within 1 hour after the start of the infusion.",
          "timeFrame": "Day 365 to Day 2,185"
        },
        {
          "measure": "Mean BL Hematocrit in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "Baseline (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Participant Hematocrit in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL Platelet Count in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Participant Platelet Count in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL Hemoglobin, Total Protein, and Albumin in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Hemoglobin, Total Protein, and Albumin in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL White Blood Cells in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in White Blood Cells in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL Liver Function Parameters in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Liver Function Parameters in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL Select Laboratory Parameters in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Select Laboratory Parameters in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean BL Serum Electrolytes in the OL Period",
          "description": "Mean baseline values are those that are reported for each cohort at each time point on Day 365 to Day 2,185.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        },
        {
          "measure": "Mean Change From BL in Serum Electrolytes in the OL Period",
          "description": "All changes in participant laboratory parameters were monitored on each day of study drug administration.",
          "timeFrame": "BL (Day 0), Day 365, Day 729, Day 1,093, Day 1,457, Day 1,821, Day 1,905, Day 1,989, Day 2,073, Day 2,185"
        }
      ],
      "secondaryOutcomes": [
        {
          "measure": "Mean Number of Tender Joints and Swollen Joints at DB BL",
          "timeFrame": "BL (Day 0)"
        },
        {
          "measure": "Mean DB BL Participant Physical Pain Assessment, Participant Global Assessment, and Physician Global Assessment",

In [51]:
# contains phase
print(json.dumps(nct_info["protocolSection"]["designModule"], indent=2))

{
  "studyType": "INTERVENTIONAL",
  "phases": [
    "PHASE3"
  ],
  "designInfo": {
    "allocation": "RANDOMIZED",
    "interventionModel": "PARALLEL",
    "primaryPurpose": "TREATMENT",
    "maskingInfo": {
      "masking": "DOUBLE",
      "whoMasked": [
        "PARTICIPANT",
        "INVESTIGATOR"
      ]
    }
  },
  "enrollmentInfo": {
    "count": 1250,
    "type": "ACTUAL"
  }
}

In [52]:
# contains timestamp and status
# interested by COMPLETED status, handle TERMINATED cases - ignore or check reasons why
print(json.dumps(nct_info["protocolSection"]["statusModule"] , indent=2))

{
  "statusVerifiedDate": "2011-10",
  "overallStatus": "COMPLETED",
  "expandedAccessInfo": {
    "hasExpandedAccess": false
  },
  "startDateStruct": {
    "date": "2002-12"
  },
  "primaryCompletionDateStruct": {
    "date": "2009-10",
    "type": "ACTUAL"
  },
  "completionDateStruct": {
    "date": "2009-10",
    "type": "ACTUAL"
  },
  "studyFirstSubmitDate": "2002-11-02",
  "studyFirstSubmitQcDate": "2002-11-12",
  "studyFirstPostDateStruct": {
    "date": "2002-11-13",
    "type": "ESTIMATED"
  },
  "resultsFirstSubmitDate": "2011-03-28",
  "resultsFirstSubmitQcDate": "2011-10-26",
  "resultsFirstPostDateStruct": {
    "date": "2011-12-05",
    "type": "ESTIMATED"
  },
  "lastUpdateSubmitDate": "2011-10-26",
  "lastUpdatePostDateStruct": {
    "date": "2011-12-05",
    "type": "ESTIMATED"
  }
}

In [ ]:
# can use a hearistic on the success of the trial - e.g. median p.value :)

# maybe this strategy:
#   success: status==COMPLETED and pvalues ok 
#   failure: status == COMPLETED and pvalues not ok
#   unknown: status != COMPLETED or no results (but maybe need to find out why not completed)

if nct_info["hasResults"]:
    measures = nct_info["resultsSection"]["outcomeMeasuresModule"]["outcomeMeasures"]
    for measure in measures:
        if "analyses" in measure:
            print(measure["analyses"][0]["pValue"])
else:
    # TODO: why sometimes no results
    print("No results")

<0.001
<0.001
0.029
<0.001
<0.001
<0.001
<0.001
<0.001
<0.001
<0.001
<0.001
0.002

## Embeddings Extraction

To create a score o semantic proximity between drugs and diseases.

Can compare only embeddings of names of drugs and diseases or full textual descriptions (e.g. DrugBank or CheMBL description for drugs and  MeSH or PubMed summary for diseases) using cosine similrity.

SapBERT (for concept-level similarity) or PubMedBERT (for descriptive embeddings)

maybe Bio-Bert?

all from `transformers` module

Can do both word and description embeddings (but compare only those of the same kind)